name: All builds
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
      - name: Run tests
        run: go test -v -race ./...
      - name: Run go vet
        run: go vet ./...
